### PR TITLE
Make compatible with Good 6.4

### LINKED ISSUE #5: Make compatible with Good 6.4
See #2

### PR DESCRIPTION
**Pull request by dmacosta**
Closes #5

Misc

- Add support for creating instance without invoking constructor
- Remove sinon as dependency
- Fix tests

### CODE REVIEW

**Comment by dmacosta** [comment]
@PaulMougel I've mixed your changes with fixes on the tests. Would you mind testing if it's working for you?. I'll merge this with master if so.

**Comment by PaulMougel** [comment]
Awesome, thank you for looking into this!

I think there's an issue with regards to how the library [handles the channel option](https://github.com/dmacosta/good-slack/blob/fix-5/lib/index.js#L26).

The configuration I used to send was the following:

```
{
    "url": "<my slack hook URL>",
    "slack": {
      "channel": "@paul",
      "icon_url": "<some URL>",
      "username": "Hapi Node.js"
    }
  }
```

which now doesn't work: `Error: channel must be a string`.

But if I use 
```
{
    "url": "<my slack hook URL>",
    "channel": "@paul",
    "icon_url": "<some URL>",
    "username": "Hapi Node.js"
  }
```

the object instantiation works, but none of the settings (except from `url`) is taken into account.

If I drop the Hoek check on `channel` and use the first configuration object, then everything works as expected.
Should we drop the Hoek check? IIRC, Slack webhook integrations set up a default channel.

**Comment by dmacosta** [comment]
@PaulMougel Good call. I changed it to make `config.channel` optional. It should be working now with the first config snippet. I still need to update the README to reflect the correct values.

**Comment by cxam** [comment]
Good work on this. I've tested all the events and seems to work as expected. Would you like me to submit a PR for the fallback fields?

**Comment by dmacosta** [comment]
@cxam Thanks for the feedback!. Sure thing, contributions are always welcome. I'll merge this right away and publish the new version.

**Pull request merged**
